### rota localhost/home/user
@baseUrl = http://localhost:5000

###
GET {{baseUrl}}/api/docs
### POSTS ###
### findAll
GET {{baseUrl}}/api/posts/

### findOne
GET {{baseUrl}}/api/posts/1

### create
POST {{baseUrl}}/api/posts/
Content-Type: application/json

{
  "title": "Meu post",
  "body": "C",
  "authorId": 1,
  "categoryId": 2
}

### update
PUT {{baseUrl}}/api/posts/id

### delete
DELETE {{baseUrl}}/api/posts/1

### POSTS ###





### USERS ###
### findAll
GET {{baseUrl}}/api/users

### findOne
GET {{baseUrl}}/api/users/5

### create
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "email": "joao5@gmail.com",
  "username": "joaov6",
  "password": "joao12356"
}

### update
PATCH  {{baseUrl}}/api/users/1
Content-Type: application/json

{
  "password": "joao UPDATE"
}

### delete
DELETE {{baseUrl}}/api/users/id
### USERS ###


### CATEGORY ###
### findAll
GET {{baseUrl}}/api/categories

### findOne
GET {{baseUrl}}/api/categories/50

### create
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "title": "js",
  "description":  "Nest and fastfy"
}

### update
PATCH {{baseUrl}}/api/categories/2
Content-Type: application/json

{
  "title": "js",
  "description":  "Nest, fastfy and React"
}

### delete
DELETE {{baseUrl}}/api/categories/3
### CATEGORY ###