### rota localhost/home/user
@baseUrl = http://localhost:3000
### messages routes ###

### findAll
GET {{baseUrl}}/messages/

### findOne
GET {{baseUrl}}/messages/2/

### create
POST {{baseUrl}}/messages/
Content-Type: application/json

 {
    "text": "novo recado",
    "de": "maria",
    "for": "joao",
    "read": true,
    "data": "2025-06-03T13:02:06.580Z"
}

### update 
PATCH {{baseUrl}}/messages/2/
Content-Type: application/json

 {
    "text": "Novo recado",
    "de": "maria",
    "for": "joao",
    "read": true,
    "data": "2025-06-03T13:02:06.580Z"
}
### delete 
DELETE {{baseUrl}}/messages/2/


# ### exemplo de rota modulov1
# # @name appControllerGetUser
# GET  {{baseUrl}}/home/user

# ### outra rota
# # @name appControlerRotaTest
# GET {{baseUrl}}/home/test/

# ### manual-concepts
# # @name manualConceptsController
# GET {{baseUrl}}/manual-concepts/

# ### automatic-concepts
# # @name automatic-conceptsController
# GET {{baseUrl}}/automatic-concepts/